### ISSUE TITLE
Bug in FortunaPRNG::CountInc()

### ISSUE THREAD

**Issue by vedadkajtaz** [ryco117/Fortuna#1]
Hello,

```
void FortunaPRNG::CountInc()
{
	unsigned char i = 0;
	while(true)
	{
		Counter[i] += 1;
		if(Counter[i] == 0 && i != 15)	//Continue loop if carry and wasn't last byte
			continue;
		else							//Unnecessary else..
			break;
	}
	return;
}
```

`i` never gets updated in the loop, `i != 15` is always true.

**Comment by ryco117** [comment]
Hi, thanks for letting me know! That was a huge oversight (that I apparently fixed in my CryptoLibrary repository, a consolidation of my various cryptographic primitives, but forgot to fix in the original!)
Fixed with commit [071fe33](https://github.com/ryco117/Fortuna/commit/071fe33222ad0197d3009ff5b97aeca95a9353fe)
